module.exports = {
  TOKEN_VALIDO: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjUsImVtYWlsIjoidGFuaWEucGVyZXouZEB1Y2IuZWR1LmJvIiwiaWF0IjoxNzgwMzM5MDY0LCJleHAiOjE3ODAzNjQyNjR9.CDPwIrN6G-ZDJh2I4Tgyw4C_Kn_-xpXuof8CoKg7AQ8',
  DOMINIO_PERMITIDO: 'ucb.edu.bo'
};
